### ISSUE TITLE
Email opt-in/out option

### ISSUE THREAD

**Issue by kklee998** [apusds/cms#19]
**Is your feature request related to a problem? Please describe.**
Users should be able to opt-in to our email(s) when signin up, and our emails should contain a way from them to opt out

**Describe the solution you'd like**
I am pretty sure a simple wantsEmail boolean column will suffice ... but need to discuss with @InspectorGadget 

**Describe alternatives you've considered**
Mailchimp? it's free up-to first 2000

**Additional context**

**Comment by almondheng** [comment]
Opt-in should be mandatory

**Comment by InspectorGadget** [comment]
Discussed with KK, he should be able to lead the Development on this Feature.

**Comment by kklee998** [comment]
I don't mind doing the dev, but i wanna do the prod deployment too :3

**Comment by InspectorGadget** [comment]
The production deployment is not as easy as setting up the Database and moving in the new Files. It is more than that since the CMS is running on a Custom Infrastructure that was made by me and the Database itself is appended with my main Database Manager. I can't give access to one DB w/o giving you access to the whole Cluster.

**Comment by InspectorGadget** [comment]
Will be implemented on CMS 2.0
